[package]
name = "cw-paginate-storage"
authors = ["ekez ekez@withoutdoing.com"]
description = "A package for paginating cosmwasm maps."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std ={ workspace = true ,default-features = false}
# cosmwasm-storage = { workspace = true }
secret-storage-plus = { workspace = true, default-features = false}
secret-toolkit = { workspace = true, default-features = false}
serde = { workspace = true }

[dev-dependencies]
secret-multi-test = { workspace = true }