[package]
name = "dao-voting"
authors = ["ekez ekez@withoutdoing.com"]
description = "Types and methods for CosmWasm DAO voting."
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
cosmwasm-std ={ workspace = true }
cosmwasm-schema = { workspace = true }
thiserror = { workspace = true }
secret-toolkit = { workspace = true }
dao-interface = { workspace = true }
dao-dao-macros = { workspace = true }
cw-denom = { workspace = true }
secret-utils = { workspace = true }
secret-storage-plus = { workspace = true }
serde ={ workspace = true }
schemars ={ workspace = true }
secret-cw-controllers ={ workspace = true }
